[build]
  functions = "netlify/functions"

[[redirects]]
  # Ensure function endpoints are served by Netlify functions
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  # Then your SPA fallback
  from = "/*"
  to = "/index.html"
  status = 200
